version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
    #- JAVA_HOME: C:\Program Files\Java\jdk1.8.0
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
install:
  - ps: |
      if (!(Test-Path -Path "C:\maven" )) {
        MkDir("C:\maven")
        Write-Host "Downloading Maven..."
        (new-object System.Net.WebClient).DownloadFile('http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip', 'C:\maven\bin.zip')
        Write-Host "Unzipping Maven..."
        $shell = New-Object -ComObject shell.application
        $zip = $shell.NameSpace("C:\maven\bin.zip")
        MkDir("C:\maven\3.2.5")
        foreach ($item in $zip.items()) {
          $shell.Namespace("C:\maven\3.2.5").CopyHere($item)
        }
      }
      Dir -Recurse C:\maven | Get-Childitem
  - cmd: SET PATH=C:\maven\3.2.5\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true
test_script:
  - mvn clean install --batch-mode -Pqulice
cache:
  - C:\maven\

